### ISSUE TITLE
When running ./vendor/bin/doctrine-module from cli within a ZF2 module a Fatal error is thrown

### ISSUE THREAD

**Issue by DannyvdSluijs** [doctrine/DoctrineORMModule#331]
```bash
Danny:~/NetBeansProjects/ZendDeveloperTools$ ./vendor/bin/doctrine-module

PHP Fatal error:  Class 'Zend\ModuleManager\Listener\ListenerOptions' not found in /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-mvc/Zend/Mvc/Service/ModuleManagerFactory.php on line 42
PHP Stack trace:
PHP   1. {main}() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/doctrine/doctrine-module/bin/doctrine-module:0
PHP   2. include() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/doctrine/doctrine-module/bin/doctrine-module:4
PHP   3. Zend\Mvc\Application::init() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/doctrine/doctrine-module/bin/doctrine-module.php:48
PHP   4. Zend\ServiceManager\ServiceManager->get() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-mvc/Zend/Mvc/Application.php:253
PHP   5. Zend\ServiceManager\ServiceManager->create() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-servicemanager/Zend/ServiceManager/ServiceManager.php:503
PHP   6. Zend\ServiceManager\ServiceManager->doCreate() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-servicemanager/Zend/ServiceManager/ServiceManager.php:569
PHP   7. Zend\ServiceManager\ServiceManager->createFromFactory() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-servicemanager/Zend/ServiceManager/ServiceManager.php:609
PHP   8. Zend\ServiceManager\ServiceManager->createServiceViaCallback() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-servicemanager/Zend/ServiceManager/ServiceManager.php:1035
PHP   9. call_user_func() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-servicemanager/Zend/ServiceManager/ServiceManager.php:905
PHP  10. Zend\Mvc\Service\ModuleManagerFactory->createService() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-servicemanager/Zend/ServiceManager/ServiceManager.php:0

Fatal error: Class 'Zend\ModuleManager\Listener\ListenerOptions' not found in /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-mvc/Zend/Mvc/Service/ModuleManagerFactory.php on line 42

Call Stack:
    0.0001     631944   1. {main}() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/doctrine/doctrine-module/bin/doctrine-module:0
    0.0003     649992   2. include('/home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/doctrine/doctrine-module/bin/doctrine-module.php') /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/doctrine/doctrine-module/bin/doctrine-module:4
    0.0036     940424   3. Zend\Mvc\Application::init() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/doctrine/doctrine-module/bin/doctrine-module.php:48
    0.0064    1437752   4. Zend\ServiceManager\ServiceManager->get() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-mvc/Zend/Mvc/Application.php:253
    0.0065    1438824   5. Zend\ServiceManager\ServiceManager->create() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-servicemanager/Zend/ServiceManager/ServiceManager.php:503
    0.0065    1438824   6. Zend\ServiceManager\ServiceManager->doCreate() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-servicemanager/Zend/ServiceManager/ServiceManager.php:569
    0.0065    1438904   7. Zend\ServiceManager\ServiceManager->createFromFactory() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-servicemanager/Zend/ServiceManager/ServiceManager.php:609
    0.0068    1478584   8. Zend\ServiceManager\ServiceManager->createServiceViaCallback() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-servicemanager/Zend/ServiceManager/ServiceManager.php:1035
    0.0069    1479088   9. call_user_func() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-servicemanager/Zend/ServiceManager/ServiceManager.php:905
    0.0069    1479160  10. Zend\Mvc\Service\ModuleManagerFactory->createService() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-servicemanager/Zend/ServiceManager/ServiceManager.php:0
```

After some initial debugging it seems that 
"zendframework/zend-modulemanager": "2.2.6",
"zendframework/zend-loader": "2.2.6",
are missing, as this brings the fatal error back to:

```bash
PHP Fatal error:  Uncaught exception 'Zend\ModuleManager\Exception\InvalidArgumentException' with message 'Parameter to Zend\ModuleManager\ModuleManager's Zend\ModuleManager\ModuleManager::setModules method must be an array or implement the Traversable interface' in /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-modulemanager/Zend/ModuleManager/ModuleManager.php:235
Stack trace:
#0 /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-modulemanager/Zend/ModuleManager/ModuleManager.php(63): Zend\ModuleManager\ModuleManager->setModules(NULL)
#1 /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-mvc/Zend/Mvc/Service/ModuleManagerFactory.php(120): Zend\ModuleManager\ModuleManager->__construct(NULL, Object(Zend\EventManager\EventManager))
#2 [internal function]: Zend\Mvc\Service\ModuleManagerFactory->createService(Object(Zend\ServiceManager\ServiceManager), 'modulemanager', 'ModuleManager')
#3 /home/dvandersluijs/NetBeansProjects/ZendDevel in /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-servicemanager/Zend/ServiceManager/ServiceManager.php on line 912

Fatal error: Uncaught exception 'Zend\ModuleManager\Exception\InvalidArgumentException' with message 'Parameter to Zend\ModuleManager\ModuleManager's Zend\ModuleManager\ModuleManager::setModules method must be an array or implement the Traversable interface' in /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-servicemanager/Zend/ServiceManager/ServiceManager.php on line 912

Zend\ModuleManager\Exception\InvalidArgumentException: Parameter to Zend\ModuleManager\ModuleManager's Zend\ModuleManager\ModuleManager::setModules method must be an array or implement the Traversable interface in /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-modulemanager/Zend/ModuleManager/ModuleManager.php on line 235

Call Stack:
    0.0002     631944   1. {main}() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/doctrine/doctrine-module/bin/doctrine-module:0
    0.0005     649992   2. include('/home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/doctrine/doctrine-module/bin/doctrine-module.php') /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/doctrine/doctrine-module/bin/doctrine-module:4
    0.0041     942048   3. Zend\Mvc\Application::init() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/doctrine/doctrine-module/bin/doctrine-module.php:48
    0.0082    1439312   4. Zend\ServiceManager\ServiceManager->get() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-mvc/Zend/Mvc/Application.php:253
    0.0082    1440384   5. Zend\ServiceManager\ServiceManager->create() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-servicemanager/Zend/ServiceManager/ServiceManager.php:503
    0.0082    1440384   6. Zend\ServiceManager\ServiceManager->doCreate() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-servicemanager/Zend/ServiceManager/ServiceManager.php:569
    0.0082    1440464   7. Zend\ServiceManager\ServiceManager->createFromFactory() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-servicemanager/Zend/ServiceManager/ServiceManager.php:609
    0.0091    1480176   8. Zend\ServiceManager\ServiceManager->createServiceViaCallback() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-servicemanager/Zend/ServiceManager/ServiceManager.php:1035
    0.0092    1480680   9. call_user_func() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-servicemanager/Zend/ServiceManager/ServiceManager.php:905
    0.0092    1480752  10. Zend\Mvc\Service\ModuleManagerFactory->createService() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-servicemanager/Zend/ServiceManager/ServiceManager.php:0
    0.0266    3149984  11. Zend\ModuleManager\ModuleManager->__construct() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-mvc/Zend/Mvc/Service/ModuleManagerFactory.php:120
    0.0266    3149984  12. Zend\ModuleManager\ModuleManager->setModules() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-modulemanager/Zend/ModuleManager/ModuleManager.php:63

Zend\ServiceManager\Exception\ServiceNotCreatedException: An exception was raised while creating "ModuleManager"; no instance returned in /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-servicemanager/Zend/ServiceManager/ServiceManager.php on line 912

Call Stack:
    0.0002     631944   1. {main}() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/doctrine/doctrine-module/bin/doctrine-module:0
    0.0005     649992   2. include('/home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/doctrine/doctrine-module/bin/doctrine-module.php') /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/doctrine/doctrine-module/bin/doctrine-module:4
    0.0041     942048   3. Zend\Mvc\Application::init() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/doctrine/doctrine-module/bin/doctrine-module.php:48
    0.0082    1439312   4. Zend\ServiceManager\ServiceManager->get() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-mvc/Zend/Mvc/Application.php:253
    0.0082    1440384   5. Zend\ServiceManager\ServiceManager->create() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-servicemanager/Zend/ServiceManager/ServiceManager.php:503
    0.0082    1440384   6. Zend\ServiceManager\ServiceManager->doCreate() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-servicemanager/Zend/ServiceManager/ServiceManager.php:569
    0.0082    1440464   7. Zend\ServiceManager\ServiceManager->createFromFactory() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-servicemanager/Zend/ServiceManager/ServiceManager.php:609
    0.0091    1480176   8. Zend\ServiceManager\ServiceManager->createServiceViaCallback() /home/dvandersluijs/NetBeansProjects/ZendDeveloperTools/vendor/zendframework/zend-servicemanager/Zend/ServiceManager/ServiceManager.php:1035
```

Steps to reproduce:

```bash
git clone https://github.com/zendframework/ZendDeveloperTools.git
cd ZendDeveloperTools/
composer require "doctrine/doctrine-orm-module" "0.8.*"
composer update
> config/application.config.php
./vendor/bin/doctrine-module

# optional
composer require "zendframework/zend-modulemanager" "2.2.6"
composer require "zendframework/zend-loader" "2.2.6"
```

**Comment by Moring** [comment]
I have also seen this error when there is an empty 'init_autoloader.php' in the ZF2 application root directory.  Doctrine orm module will short circuit to that autoloader if it exists, over the one in the vendor directory.

**Comment by gianarb** [comment]
Hi! I close this issue, if this problem persist write here and I reopen
Thanks
