### ISSUE TITLE
Master-slave connection incongruence

### ISSUE THREAD

**Issue by Gamempire** [doctrine/DoctrineORMModule#345]
Hi all, I tried in implementing a master-slave connection with DoctrineORM but I have encountered a problem, probably due to an error in the documentation.

This is the default connection of DoctrineORM like described here: https://github.com/doctrine/DoctrineORMModule#connection-settings

    'doctrine' => array(
        'connection' => array(
            'orm_default' => array(
                'driverClass' => 'Doctrine\DBAL\Driver\PDOMySql\Driver',
                'params' => array(
                    'host'     => 'localhost',
                    'port'     => '3306',
                    'user'     => 'XXX',
                    'password' => 'XXX',
                    'dbname'   => 'XXX',
                )
            )
        ),
    ),

I tried editing it following this doc: https://github.com/doctrine/dbal/blob/149f18001a459c22e1f2a87903e455eb89c1b4de/lib/Doctrine/DBAL/Connections/MasterSlaveConnection.php#L68-L76

So...

    'doctrine' => array(
        'connection' => array(
            'orm_default' => array(
                'wrapperClass' => 'Doctrine\DBAL\Connections\MasterSlaveConnection',
                'driver' => 'Doctrine\DBAL\Driver\PDOMySql\Driver',
                'master' => array(
	                'host'     => 'localhost',
	                'port'     => '3306',
	                'user'     => 'XXX',
	                'password' => 'XXX',
	                'dbname'   => 'XXX',
                ),
                'slaves' => array(
	                array(
		                'host'     => 'localhost',
		                'port'     => '3306',
		                'user'     => 'XXX2',
		                'password' => 'XXX2',
		                'dbname'   => 'XXX2',
	                )
                ),
            )
        ),
    ),

But I received the following error:

```
Fatal error: Uncaught exception 'Zend\Stdlib\Exception\BadMethodCallException' with message 'The option "master" does not have a matching setMaster setter method which must be defined' in /home/siti/mywebsite.com/stable/vendor/zendframework/zendframework/library/Zend/Stdlib/AbstractOptions.php:96 Stack trace: #0 /home/siti/mywebsite.com/stable/vendor/zendframework/zendframework/library/Zend/Stdlib/AbstractOptions.php(57): Zend\Stdlib\AbstractOptions->__set('master', Array) #1 /home/siti/mywebsite.com/stable/vendor/zendframework/zendframework/library/Zend/Stdlib/AbstractOptions.php(32): Zend\Stdlib\AbstractOptions->setFromArray(Array) #2 /home/siti/mywebsite.com/stable/vendor/doctrine/doctrine-module/src/DoctrineModule/Service/AbstractFactory.php(92): Zend\Stdlib\AbstractOptions->__construct(Array) #3 /home/siti/mywebsite.com/stable/vendor/doctrine/doctrine-orm-module/src/DoctrineORMModule/Service/DBALConnectionFactory.php(42): DoctrineModule\Service\AbstractFactory->getOptions(Object(Zend\ServiceManager\ServiceManager), 'connection') #4 /hom in /home/siti/mywebsite.com/stable/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php on line 909
```

I tried also:
- writing `'driverClass'` instead of `'driver'`
- putting `'master'` and `'slaves'` inside `'params'`

but the code still not work. Any idea?

**Comment by Gamempire** [comment]
:up:

**Comment by Gamempire** [comment]
Solved in a non really clean way, but it works.
```
if (getenv('MYSQL_SLAVE_HOST') == '' || Console::isConsole()) {
    $connectionParams = array(
        'driverClass' => 'Doctrine\DBAL\Driver\PDOMySql\Driver',
        'params' => array(
            'host'     => getenv('MYSQL_MASTER_HOST'),
            'port'     => getenv('MYSQL_MASTER_PORT'),
            'user'     => getenv('MYSQL_MASTER_USER'),
            'password' => getenv('MYSQL_MASTER_PWD'),
            'dbname'   => getenv('MYSQL_MASTER_DB'),
        ),
    );
}
else {
    $connectionParams = array(
        'wrapperClass' => 'Doctrine\DBAL\Connections\MasterSlaveConnection',
        'params' => array(
            'driver' => 'pdo_mysql',
            'master' => array(
                'host'     => getenv('MYSQL_MASTER_HOST'),
                'port'     => getenv('MYSQL_MASTER_PORT'),
                'user'     => getenv('MYSQL_MASTER_USER'),
                'password' => getenv('MYSQL_MASTER_PWD'),
                'dbname'   => getenv('MYSQL_MASTER_DB'),
            ),
            'slaves' => array(
                array(
                    'host'     => getenv('MYSQL_SLAVE_HOST'),
                    'port'     => getenv('MYSQL_SLAVE_PORT'),
                    'user'     => getenv('MYSQL_SLAVE_USER'),
                    'password' => getenv('MYSQL_SLAVE_PWD'),
                    'dbname'   => getenv('MYSQL_SLAVE_DB'),
                ),
            ),
        ),
    );
}
```
