### ISSUE TITLE
Migration path not found

### ISSUE THREAD

**Issue by wilariz** [doctrine/DoctrineORMModule#427]
Hi, I recently update version of doctrine/migrations from 1.0 alpha to estable via DoctrineOrmModule.
My project zf2 have 2 environments (web and console), both work fine before the update. Well now I have a problem with migration configuration when I use via console, the path by default ("data/DoctrineOrmModule/Migrations") is not found. One of my question is why try to load or use migrations service in a process than don't use Migrations.
Here is my error trace:
```
PHP Warning:  array_map(): An error occurred while invoking the map callback in /home/jchevarria/projects/bookingmotor/vendor/doctrine/doctrine-orm-module/src/DoctrineORMModule/Module.php on line 138

Warning: array_map(): An error occurred while invoking the map callback in /home/jchevarria/projects/bookingmotor/vendor/doctrine/doctrine-orm-module/src/DoctrineORMModule/Module.php on line 138
PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Cannot load migrations from "data/DoctrineORMModule/Migrations" because it is not a valid directory' in /home/jchevarria/projects/bookingmotor/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Finder/AbstractFinder.php:38
Stack trace:
#0 /home/jchevarria/projects/bookingmotor/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Finder/RecursiveRegexFinder.php(36): Doctrine\DBAL\Migrations\Finder\AbstractFinder->getRealPath('data/DoctrineOR...')
#1 /home/jchevarria/projects/bookingmotor/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Configuration/Configuration.php(649): Doctrine\DBAL\Migrations\Finder\RecursiveRegexFinder->findMigrations('data/DoctrineOR...', 'DoctrineORMModu...')
#2 /home/jchevarria/projects/bookingmotor/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Configuration/Configuration.php(293): Doctrine\DBAL\Migrations\Configuration\Configuration->findMigrations('data/DoctrineOR...')
#3 /home/jchevarria/projects/b in /home/jchevarria/projects/bookingmotor/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 946

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Cannot load migrations from "data/DoctrineORMModule/Migrations" because it is not a valid directory' in /home/jchevarria/projects/bookingmotor/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Finder/AbstractFinder.php:38
Stack trace:
#0 /home/jchevarria/projects/bookingmotor/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Finder/RecursiveRegexFinder.php(36): Doctrine\DBAL\Migrations\Finder\AbstractFinder->getRealPath('data/DoctrineOR...')
#1 /home/jchevarria/projects/bookingmotor/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Configuration/Configuration.php(649): Doctrine\DBAL\Migrations\Finder\RecursiveRegexFinder->findMigrations('data/DoctrineOR...', 'DoctrineORMModu...')
#2 /home/jchevarria/projects/bookingmotor/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Configuration/Configuration.php(293): Doctrine\DBAL\Migrations\Configuration\Configuration->findMigrations('data/DoctrineOR...')
#3 /home/jchevarria/projects/b in /home/jchevarria/projects/bookingmotor/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 946
```
I hope you can help with this problem.

Good Regards.

**Comment by Ocramius** [comment]
> why try to load or use migrations service in a process than don't use Migrations.

This is because you have the migrations lib installed, so the CLI wants to initialize the migrations commands.

**Comment by wilariz** [comment]
ok I understand but What is the solution for my issue, I need that both environments work.. now I configured a local way the path migrations, but what about when I need upgrade in live or maybe other team mate..

**Comment by Ocramius** [comment]
Possible solutions:
 - point the config for the fixtures to an empty directory
 - override the CLI services

**Comment by wilariz** [comment]
Ok I'll try.
thank you
